import Head from "next/head";
import { Montserrat } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Card from "@/components/Card";


const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // Добавьте нужные веса
  variable: "--font-montserrat", // Создаст CSS-переменную
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${montserrat.variable}`}
      >
        <main className={styles.main}>
          <Card/>
        </main>
      </div>
    </>
  );
}
